const Disturbution=[
   {id:1 ,
   project: "یکپارچه‌سازی سیستم کنترل دسترس" ,
organization: "مدیریت کسب و کار مدیریت تحول دیجیتال" ,
projectManager: "میلاد هلاچیان",
projectNumber: 999,
projectStartDate: "1394/11/14",
projectFinishDate:"1399/07/02" ,
projectType: "Cost/Event(NIS)",
status: "Executive",
customer:"فولاد مبارکه" ,},
   {id:2 ,
   project: "نگهداری شبکه فولاد خراسان 98-99",
organization: "مدیریت کسب و کار شبکه و زیرساخت" ,
projectManager:"ساسان عبداله زاده" ,
projectNumber: 996,
projectStartDate:"1394/11/14" ,
projectFinishDate: "1399/06/31",
projectType: "Cost/Event(NIS)" ,
status: "pending close" ,
customer: "فولاد خراسان" ,},
   {id:3 ,
   project: "توسعه فناوری RFID فولاد مبارکه",
organization: "مدیریت کسب و کار شبکه و زیرساخت",
projectManager: "رضا اخوان",
projectNumber:994 ,
projectStartDate:"1394/11/14" ,
projectFinishDate: "1396/06/08",
projectType: "Event/Event(NIS)" ,
status:"pending close"  ,
customer:"فولاد مبارکه" ,},
   {id:4 ,
   project:"تامین تجهیزات موردی مبارکه" ,
organization: "مدیریت کسب و کار شبکه و زیرساخت" ,
projectManager: "ساسان عبداله زاده",
projectNumber:983 ,
projectStartDate:"1394/11/14" ,
projectFinishDate:"1399/06/01" ,
projectType: "Event/Event(NIS)",
status: "pending close"  ,
customer:"فولاد مبارکه" ,},
   {id:5 ,
   project: "توسعه سیستمهای نوین مبارکه 98" ,
organization: "مدیریت کسب و کار سیستم های اطلاعاتی",
projectManager: "مسیح حاجی صادقیان",
projectNumber:952 ,
projectStartDate: "1398/01/05" ,
projectFinishDate: "1702/03/06",
projectType:  "Cost/Event(IS)",
status:"Executive" ,
customer:"فولاد مبارکه" ,},
   {id:6 ,
   project:"نگهداری شبکع فولاد سفیددشت 98" ,
organization: "مدیریت کسب و کارشبکه و زیر ساخت",
projectManager: "سینا ایرانپور",
projectNumber: 943,
projectStartDate: "1398/01/01" ,
projectFinishDate: "1700/06/12",
projectType: "Event/Event(NIS)" ,
status:"pending close" ,
customer: "شرکت فولاد سفید دشت چهارمحال بختیاری",},
   {id:7 ,
   project: "اسکادا سیالات فولاد مبارکه",
organization: "مدیریت کسب و کار اتوماسیون صنعتی",
projectManager: "احسان عبداله زاده",
projectNumber: 937,
projectStartDate: "1394/11/14",
projectFinishDate: "1398/11/14",
projectType: "Cost/Event(AUT)" ,
status: "pending close",
customer:"فولاد مبارکه" ,},
   {id:8 ,
   project: "دوبلیکشین سیکنالهای نورد سیاه",
organization: "مدیریت کسب و کار اتوماسیون صنعتی" ,
projectManager: "مهرداد صفاری پور",
projectNumber:932 ,
projectStartDate:"1397/11/01",
projectFinishDate:  "1398/11/14",
projectType: "Cost/Event(AUT)",
status: "pending close",
customer:"فولاد مبارکه" ,},
   {id:9 ,
   project:" امیر کبیر کاشان CGL سیستم کنترل " ,
organization: "مدیریت کسب و کار اتوماسیون صنعتی",
projectManager: "شاهین خسرویان",
projectNumber: 905,
projectStartDate: "1397/06/10",
projectFinishDate: "1398/04/01",
projectType:"Cost/Event(AUT)" ,
status: "pending close",
customer: "فولاد امیرکبیر کاشان" ,},
   {id:10 ,
   project: "درایوهای نورد گرم فولاد مبارکه" ,
organization: "مدیریت کسب و کار اتوماسیون صنعتی",
projectManager: "علی طالبی",
projectNumber: 901,
projectStartDate: "1397/05/01",
projectFinishDate: "1399/12/10",
projectType:"Cost/Event(AUT)" ,
status: "Executive",
customer: "شرکت ایراسکو" ,},
   {id:11 ,
   project: "دارایی ثابت" ,
organization: "شرکت ایریسا",
projectManager: "ایرج فخری",
projectNumber: 900,
projectStartDate: "1398/03/19",
projectFinishDate: "1419/03/20",
projectType: "capital",
status:"submitted" ,
customer:"" ,},
   {id:12 ,
   project: "طراحی campus فولاد مبارکه" ,
organization: "مدیریت کسب و کارشبکه و زیر ساخت" ,
projectManager: "سینا ایرانپور",
projectNumber: 872,
projectStartDate: "1397/01/01",
projectFinishDate: "1400/01/17",
projectType: "Cost/Event(NIS)",
status:"Executive" ,
customer: "فولاد مبارکه",},
   {id:13 ,
   project:"اتوماسیون سطح سه فولاد سیا" ,
organization: "مدیریت کسب و کار اتوماسیون صنعتی",
projectManager: "مسعود اعظمی بیرانوند",
projectNumber: 861,
projectStartDate:"1396/12/01" ,
projectFinishDate: "1398/12/28",
projectType:"Cost/Event(AUT)" ,
status:"Executive" ,
customer: "فولاد مبارکه",},
];

export default Disturbution;